name: image_hoster
description: Isu practice

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  flutter_svg: ^2.0.6
  mask_text_input_formatter: ^2.4.0
  pull_to_refresh: ^2.0.0
  go_router: ^8.0.3
  intl: ^0.18.0
  flutter_flavor: ^3.1.1
  get_it: ^7.6.0
  injectable: ^2.1.1
  equatable: ^2.0.5
  retrofit: ^4.0.1
  dio: ^5.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  rxdart: ^0.27.7
  google_fonts: ^5.0.0
  flutter_dropzone: ^3.0.5
  file_picker: ^5.3.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  flutter_flavorizr: ^2.1.6
  build_runner: ^2.4.4
  injectable_generator: ^2.1.5
  hive_generator: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

flutter_intl:
  enabled: true